//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_first_demo_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int TeachId { get; set; }
        public string Name { get; set; }
    }
}
